/**
 * Exports compiled ABIs + deployment bytecode into the frontend so the React
 * app can deploy and interact with the contracts directly from the browser.
 *
 * Run after every `hardhat compile`:
 *   npm run build:contracts   (compile + export in one go)
 *
 * Writes: frontend/src/contracts.js
 */
const fs = require("fs");
const path = require("path");
const hre = require("hardhat");

const CONTRACTS = ["VulnerableBank", "SecureBank", "Attacker"];

async function main() {
  // Make sure artifacts exist.
  await hre.run("compile");

  const out = {};
  for (const name of CONTRACTS) {
    const artifact = await hre.artifacts.readArtifact(name);
    out[name] = {
      abi: artifact.abi,
      bytecode: artifact.bytecode,
    };
  }

  const header =
    "// AUTO-GENERATED by scripts/export-abis.js — do not edit by hand.\n" +
    "// Regenerate with:  npm run build:contracts\n\n";

  const body =
    "export const CONTRACTS = " + JSON.stringify(out, null, 2) + ";\n\n" +
    "export default CONTRACTS;\n";

  const destDir = path.join(__dirname, "..", "frontend", "src");
  fs.mkdirSync(destDir, { recursive: true });
  const dest = path.join(destDir, "contracts.js");
  fs.writeFileSync(dest, header + body);

  console.log("Wrote", dest);
  for (const name of CONTRACTS) {
    console.log(`  ${name}: abi(${out[name].abi.length} entries), bytecode(${out[name].bytecode.length} chars)`);
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
